- platform: template
  sensors:
    hallbath_motion:
      friendly_name: "Hall Bathroom Motion"
      device_class: motion
      entity_id: sensor.vision_zp3111_multisensor_4in1_burglar
      value_template: '{% if is_state("sensor.vision_zp3111_multisensor_4in1_burglar", "8") %}True{% else %}False{% endif %}'
    sdstatus:
      value_template: '{% if is_state("sensor.vision_zd2102_eu_doorwindow_sensor_access_control", "22") %}True{% else %}False{% endif %}'
      friendly_name: 'Side Door'
      entity_id: sensor.vision_zd2102_eu_doorwindow_sensor_access_control
      device_class: door
    fdstatus:
      value_template: '{% if is_state("sensor.vision_zd2102_eu_doorwindow_sensor_access_control_2", "22") %}True{% else %}False{% endif %}'
      friendly_name: 'Front Door'
      entity_id: sensor.vision_zd2102_eu_doorwindow_sensor_access_control_2
      device_class: door
    gunsafestatus:
      value_template: '{% if is_state("sensor.hank_hkzwdws01_doorwindow_sensor_access_control", "22") %}True{% else %}False{% endif %}'
      friendly_name: 'Gun Safe Door'
      entity_id: sensor.hank_hkzwdws01_doorwindow_sensor_access_control
      device_class: door
    gunsafetamper:
      value_template: '{% if is_state("sensor.hank_hkzwdws01_doorwindow_sensor_burglar", "0") %}False{% else %}True{% endif %}'
      friendly_name: 'Gun Safe Tamper'
      entity_id: sensor.hank_hkzwdws01_doorwindow_sensor_burglar
      device_class: problem
    hallbathmultisensortamper:
      value_template: '{% if is_state("sensor.vision_zp3111_multisensor_4in1_burglar", "3") %}True{% else %}False{% endif %}'
      friendly_name: 'Hall Bath Multisensor Tamper'
      entity_id: sensor.vision_zp3111_multisensor_4in1_burglar
      device_class: problem
    frontdoortamper:
      value_template: '{% if is_state("sensor.vision_zd2102_eu_doorwindow_sensor_burglar_2", "3") %}True{% else %}False{% endif %}'
      friendly_name: 'Front Door Tamper'
      entity_id: sensor.vision_zd2102_eu_doorwindow_sensor_burglar_2
      device_class: problem
    sidedoortamper:
      value_template: '{% if is_state("sensor.vision_zd2102_eu_doorwindow_sensor_burglar", "3") %}True{% else %}False{% endif %}'
      friendly_name: 'Side Door Tamper'
      entity_id: sensor.vision_zd2102_eu_doorwindow_sensor_burglar
      device_class: problem
    hallsmoke:
      value_template: '{% if is_state("sensor.first_alert_unknown_type0001_id0001_alarm_type", "1") %}True{% else %}False{% endif %}'
      friendly_name: 'Hall Smoke Detector'
      entity_id: sensor.first_alert_unknown_type0001_id0001_alarm_type
      device_class: smoke
    hvacfan:
      value_template: '{% if is_state_attr("climate.2gig_technologies_ct101_thermostat_iris_heating_1", "operating_state", "Idle") %}False{% else %}True{% endif %}'
      friendly_name: 'HVAC Blower Status'
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_heating_1
      device_class: moving
    doorsopen:
      value_template: '{% if is_state("group.doorsandwindows", "on") %}True{% else %}False{% endif %}'
      device_class: door
      delay_on: 
        minutes: 2
