homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Chicago
  whitelist_external_dirs:
    - /home/homeassistant/.homeassistant/
    - /home/homeassistant/.homeassistant/snapshots
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password  
  customize: !include customize.yaml

lovelace:
  mode: yaml
  
proximity:
  home:
    devices:
      - device_tracker.google_maps_109984549047371398743
      - device_tracker.google_maps_112651824816852593437
      - device_tracker.google_maps_106390694792046678454
      - device_tracker.google_maps_109585893024521841407
      - device_tracker.google_maps_114738066185562245505
      - device_tracker.google_maps_112049465177067192481
    tolerance: 50
    unit_of_measurement: mi
    
config:

map:

logbook:
  exclude:
    domains:
      - zwave
    entities:
      - sensor.router_wan_out
      - sensor.router_wan_in
      - input_number.internet_traffic_delta_out
      - input_number.internet_traffic_delta_in
      - automation.download_throughput_monitoring
      - automation.upload_throughput_monitoring
    
shell_command:
  getsnaps: /home/homeassistant/.homeassistant/getsnaps.sh
  
weather:
  - platform: darksky
    api_key: !secret darksky_api
    name: Weather
       
recorder:
  purge_keep_days: 180
  db_url: !secret mysql_dburl
#  exclude:
#    entities:
#      - sensor.nws_alert_count_any
#      - sensor.nws_alert_event
      
frontend:
  javascript_version: latest

media_player:
  - platform: plex
    entity_namespace: plex
    include_non_clients: false
    scan_interval: 5
    show_all_controls: false
    use_custom_entity_ids: true
    use_episode_art: false
    remove_unavailable_clients: true
    client_remove_interval: 600

cloud:

http:
  api_password: !secret api-pw
  base_url: !secret base-url
  ssl_certificate: /home/homeassistant/fullchain.pem
  ssl_key: /home/homeassistant/privkey.pem
  trusted_networks: 192.168.1.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 3
  
updater:
  include_used_components: true

discovery:

conversation:

history: !include history.yaml

sun:

notify:
  - name: email_dan
    platform: smtp
    server: !secret email_server
    port: !secret email_port
    encryption: starttls
    timeout: 10
    username: !secret email_username
    password: !secret email_password
    sender: !secret email_sender
    sender_name: Home Assistant
    recipient:
      - !secret email_dan
      - !secret email_dan_sms
  - name: email_residents
    platform: smtp
    server: !secret email_server
    port: !secret email_port
    encryption: starttls
    timeout: 10
    username: !secret email_username
    password: !secret email_password
    sender: !secret email_sender
    sender_name: Home Assistant
    recipient:
      - !secret email_dan
      - !secret email_dan_sms
      - !secret email_karla
      - !secret email_karla_sms
      - !secret email_stephen
      - !secret email_stephen_sms
      - !secret email_ericjr
      - !secret email_ericjr_sms
  - name: email_everyone
    platform: smtp
    server: !secret email_server
    port: !secret email_port
    encryption: starttls
    timeout: 10
    username: !secret email_username
    password: !secret email_password
    sender: !secret email_sender
    sender_name: Home Assistant
    recipient:
      - !secret email_dan
      - !secret email_dan_sms
      - !secret email_karla
      - !secret email_karla_sms
      - !secret email_stephen
      - !secret email_stephen_sms
      - !secret email_ericjr
      - !secret email_ericjr_sms
      - !secret email_rainne
      - !secret email_rainne_sms
  - name: push
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
    
sensor:
  !include sensors.yaml

tts:
  platform: google

mqtt:
  broker: 192.168.1.6
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_uname
  password: !secret mqtt_pw
  
device_tracker:
#  - platform: owntracks
#    max_gps_accuracy: 500
#  - platform: unifi
#    host: !secret unifi_host
#    username: !secret unifi_username
#    password: !secret unifi_password
  - platform: google_maps
    username: !secret google_username
    password: !secret google_password
    max_gps_accuracy: 500
    
group:
  !include groups.yaml

automation: 
  !include automations.yaml
  
zwave:
  usb_path: /dev/ttyUSB0
  polling_interval: 30000
  network_key: !secret zwave_netkey
  device_config: !include zwave_device_config.yaml

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db
  
camera:
  - platform: uvc
    nvr: 192.168.1.6
    port: 7080
    key: !secret uvc_key
    password: !secret uvc_password
  - platform: ffmpeg
    name: Camera (Network Rack)
    input: !secret rackcam_url
  - platform: local_file
    name: wximage
    file_path: /home/danb/hurricam/wximage.jpg
    
input_boolean:
  hvac_automation:
    name: Automagic Thermostat
    initial: on
    icon: mdi:thermometer-lines
  hvac_filter:
    name: Change HVAC Filter
    initial: off
    icon: mdi:filter-variant
    
input_datetime:
  hvac_filter_last_changed:
    name: Filter Changed On
    has_date: true
    has_time: true

input_number:
  internet_traffic_delta_in:
    min: 0
    max: 1000000000000
  internet_traffic_delta_out:
    min: 0
    max: 1000000000000
    
binary_sensor:
  !include binarysensors.yaml

alarm_control_panel:
  - platform: manual
    name: alarm
    code: !secret alarm_code
    pending_time: 0
    delay_time: 0
    trigger_time: 120
    disarmed:
      trigger_time: 0   
    armed_home:
      pending_time: 0
      delay_time: 0
      trigger_time: 120
